src/Okurdostu.Web/Controllers/LogoutController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Okurdostu.Web.Controllers
{
    public class LogoutController : Controller
    {
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Index()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return Redirect("/");
        }
    }
}

src/Okurdostu.Web/Views/Shared/_GoogleRecaptchaWarningPartial.cshtml
<div class="text-black-50 text-center small font-weight-bold">This site is protected by reCAPTCHA and the Google <a target="_blank" href="https://policies.google.com/privacy" class="od">Privacy Policy</a> and <a target="_blank" href="https://policies.google.com/terms" class="od">Terms of Service</a> apply.</div>

src/Okurdostu.Web/Views/Shared/_LayoutIntroduction.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor;
@{
    bool IsAuthenticated = HttpContextAccessor.HttpContext.User.Identity.IsAuthenticated;
}
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8"> <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> <meta http-equiv="refresh" content="120"> <title>@Html.Raw(ViewData["Title"])</title> <meta name="description" content="Öğrenci ve öğrenci dostunu bir araya getiren platform"/> <meta name="keywords" content="okurdostu,kitap,akademik burs,kitap ihtiyaç,kitap burs,öğrenci,ihtiyaç,bağış,destekleme,üniversite,eğitim,burs,burslar,bursları,bursiyer,bursiyerler,kyk @Html.Raw(","+ViewBag.Keywords)">
    @if (ViewBag.OGImage != null)
    {
        <meta name="twitter:card" content="summary" />
    }
    else
    {
        <meta name="twitter:card" content="summary_large_image" />
    }
    <meta name="twitter:site" content="@Html.Raw("@okurdostucom")"/> <meta property="og:site_name" content="Okurdostu"/> <meta property="og:locale" content="tr_TR"/> <meta property="og:url" content="Url"/> <meta property="og:title" content="@Html.Raw(ViewData["Title"])"/>
    @if (ViewBag.Description != null)
    {
        <meta property="og:description" content="@Html.Raw(ViewBag.Description)" />
    }
    else if (ViewBag.OGDescription != null)
    {
        <meta property="og:description" content="@Html.Raw(ViewBag.OGDescription)" />
    }
    else
    {
        <meta property="og:description" content="Öğrenci ve öğrenci dostunu bir araya getiren platform" />
    }
    @if (ViewBag.OGImage != null)
    {
        <meta property="og:image" content="@Html.Raw(ViewBag.OGImage)" />
        <meta property="twitter:image" content="@Html.Raw(ViewBag.OGImage)" />
    }
    else
    {
        <meta property="og:image" content="https://okurdostu.com/image/okurdostu_twitter.jpg" />
        <meta property="twitter:image" content="https://okurdostu.com/image/okurdostu_twitter.jpg" />
    }
    @if (ViewBag.OGType != null)
    {
        <meta property="og:type" content="@Html.Raw(ViewBag.OGType)" />
    }
    else
    {
        <meta property="og:type" content="website" />
    }
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" rel="stylesheet"> <link href="https://fonts.googleapis.com/css?family=Montserrat:400,600,700" rel="stylesheet"> <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700,700i" rel="stylesheet"> <script src="~/lib/jquery/dist/jquery.min.js"></script> <link href="~/css/bs-edited.css" rel="stylesheet"/> <link href="~/css/style-introduction.css" rel="stylesheet"/>
    @if (!IsAuthenticated)
    {
        <link href="~/css/preloader.css" rel="stylesheet" />
        @if (Context.Request.Path.Value.ToLower() != "/girisyap" && Context.Request.Path.Value.ToLower() != "/kaydol")
        {
            <partial name="~/Views/Shared/_ValidationScriptsPartial.cshtml" />
        }
    }
</head>
<body data-spy="scroll" data-target=".fixed-top">
    <partial name="~/Views/Shared/_SpinnerPartial.cshtml" />
    <nav class="navbar navbar-expand-md navbar-dark navbar-custom fixed-top">
        <a href="/"><span class="navbar-brand" style="cursor:pointer">Okurdostu</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-awesome fas fa-bars"></span> <span class="navbar-toggler-awesome fas fa-times"></span> </button>
        <div class="collapse navbar-collapse" id="navbar">
            <ul class="navbar-nav pt-1"> <li class="nav-item"> <a class="nav-link" href="/#header">ANASAYFA <span class="sr-only">(current)</span></a> </li><li class="nav-item"> <a class="nav-link" href="/#nasil">NASIL ÇALIŞIR?</a> </li><li class="nav-item"> <a class="nav-link" href="/sss">SSS</a> </li></ul>
            <ul class="navbar-nav ml-auto">
                @{
                    @if (!IsAuthenticated)
                    {
                        @if (Context.Request.Path.Value.ToLower() != "/girisyap" && Context.Request.Path.Value.ToLower() != "/kaydol")
                        {
                            <li class="nav-item">
                                <a class="nav-link" data-toggle="modal" data-target="#login" style="cursor:pointer;">Giriş yap</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" data-toggle="modal" data-target="#signup" style="cursor:pointer;">Kaydol</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link" href="/beta">Beta</a>
                        </li>
                    }
                    else
                    {
                        string username = HttpContextAccessor.HttpContext.User.Identity.GetUsername();
                        string picture = HttpContextAccessor.HttpContext.User.Identity.GetPhoto();
                        <li class="nav-item page-scroll">
                            @if (picture == null)
                            {
                                <div class="dropdown show">
                                    <a class="dropdown-toggle" href="" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="far fa-user lg-fa"></i>
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink" style="background-color:transparent">
                                        <a class="btn dropdown-item rounded-custom font-weight-bold" href="/beta">Beta</a>
                                        <a class="btn dropdown-item rounded-custom font-weight-bold" href="/@username">Profil</a>
                                    </div>
                                </div>
                            }
                            else
                            {
                                <div class="dropdown show">
                                    <a class="dropdown-toggle" href="" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <img src="@picture" class="rounded-circle" style="width:60px;" alt="">
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink" style="background-color:transparent">
                                        <a class="btn dropdown-item rounded-custom font-weight-bold" href="/beta">Beta</a>
                                        <a class="btn dropdown-item rounded-custom font-weight-bold" href="/@username">Profil</a>
                                    </div>
                                </div>
                            }
                        </li>
                    }
                }
            </ul>
        </div>
    </nav>
    @RenderBody()
    <div class="footer"> <div class="container"> <div class="row"> <div class="col-md-4"> <div class="footer-col"> <h4>Okurdostu</h4> <p> Öğrenci ve öğrenci dostunu bir araya getiren platform </p><p> <a class="text-center font-weight-bold od" href="mailto:info@okurdostu.com"> info@okurdostu.com </a> </p></div></div><div class="col-md-4"> <div class="footer-col middle"> <h4>Bağlantılar</h4> <span class="font-weight-bold p-large"> <a href="/beta#Feedback" class="od">Geri bildirim</a> </span> <br /> <span class="font-weight-bold p-large"> <a href="/kullanici-sozlesmesi" class="od">Kullanıcı sözleşmesi</a> </span> <br /> <span class="font-weight-bold p-large"> <a href="/gizlilik-politikasi" class="od">Gizlilik politikası</a> </span> <br /> <span class="font-weight-bold p-large"> <a href="/KVKK" class="od">KVKK</a> </span> </div></div><div class="col-md-4"> <div class="footer-col last"> <h4>SOSYAL MEDYA</h4> <span class="fa-stack"> <a href="https://twitter.com/okurdostucom" target="_blank"> <i class="fas fa-circle fa-stack-2x"></i> <i class="fab fa-twitter fa-stack-1x"></i> </a> </span> <span class="fa-stack"> <a href="https://instagram.com/okurdostucom" target="_blank"> <i class="fas fa-circle fa-stack-2x"></i> <i class="fab fa-instagram fa-stack-1x"></i> </a> </span> <span class="fa-stack"> <a href="https://www.linkedin.com/company/okurdostu/" target="_blank"> <i class="fas fa-circle fa-stack-2x"></i> <i class="fab fa-linkedin-in fa-stack-1x"></i> </a> </span> <span class="fa-stack"> <a href="https://github.com/Okurdostu" target="_blank"> <i class="fas fa-circle fa-stack-2x"></i> <i class="fab fa-github fa-stack-1x"></i> </a> </span> </div></div></div><center> <span class="font-weight-bold small">&copy; @DateTime.Now.Year Okurdostu</span> </center> </div></div>
    @if (Context.Request.Path.Value.ToLower() != "/girisyap" && Context.Request.Path.Value.ToLower() != "/kaydol" && !IsAuthenticated)
    {
        <div class="modal fade" id="signup" tabindex="-1" role="dialog" aria-hidden="true"> <div class="modal-dialog modal-lg modal-dialog-centered" role="document"> <div class="modal-content" style="background: transparent;"> <div class="modal-body p-0" style="border-radius: 25px;"> <partial name="~/Views/SignUp/_PartialSignUpForm.cshtml"> </div></div></div></div><div class="modal fade" id="login" tabindex="-1" role="dialog" aria-hidden="true"> <div class="modal-dialog modal-dialog-centered" role="document"> <div class="modal-content" style="background: transparent;"> <div class="modal-body p-0" style="border-radius: 25px;"> <partial name="~/Views/Login/_PartialLoginForm.cshtml"> </div></div></div></div>
    }
    <script src="~/js/showhidepass.js"></script> <script src="~/js/bootstrap.min.js"></script> <script src="~/js/script-introduction.js"></script> <script async src="https://www.googletagmanager.com/gtag/js?id=UA-13125894-3"></script> <script>window.dataLayer=window.dataLayer || []; function gtag(){dataLayer.push(arguments);}gtag('js', new Date()); gtag('config', 'UA-13125894-3'); </script>
</body>
</html>

src/Okurdostu.Web/Views/Shared/_LayoutOkurdostu.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor;
@{
    bool IsAuthenticated = HttpContextAccessor.HttpContext.User.Identity.IsAuthenticated;
}
<!DOCTYPE html>
<html lang="tr">
<head>
    @Html.Raw(ViewBag.Meta)
    <meta charset="utf-8"> <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> <title>@Html.Raw(ViewData["Title"])</title> <meta name="keywords" content="okurdostu,kitap,akademik burs,kitap ihtiyaç,kitap burs,öğrenci,ihtiyaç,bağış,destekleme,üniversite,eğitim,burs,burslar,bursları,bursiyer,bursiyerler,kyk"> 
    @if (ViewData["Description"] != null)
    {
        <meta name="description" content="@Html.Raw(ViewData["Description"])">
    }
    else
    {
        <meta name="description" content="Öğrenci ve öğrenci dostunu bir araya getiren platform" />
    }
    @if (ViewData["OGImage"] != null)
    {
        <meta name="twitter:card" content="summary" />
    }
    else
    {
        <meta name="twitter:card" content="summary_large_image" />
    }
    <meta name="twitter:site" content="@Html.Raw("@okurdostucom")"/> <meta property="og:site_name" content="Okurdostu"/> <meta property="og:locale" content="tr_TR"/> <meta property="og:url" content="@Context.Request.GetDisplayUrl()"/> <meta property="og:title" content="@Html.Raw(ViewData["Title"])"/>
    @if (ViewData["Description"] != null)
    {
        <meta property="og:description" content="@Html.Raw(ViewData["Description"])" />
    }
    else
    {
        <meta property="og:description" content="Öğrenci ve öğrenci dostunu bir araya getiren platform" />
    }
    @if (ViewData["OGImage"] != null)
    {
        <meta property="og:image" content="@Html.Raw(ViewData["OGImage"])" />
        <meta property="twitter:image" content="@Html.Raw(ViewData["OGImage"])" />
    }
    else
    {
        <meta property="og:image" content="https://okurdostu.com/image/okurdostu_twitter.jpg" />
        <meta property="twitter:image" content="https://okurdostu.com/image/okurdostu_twitter.jpg" />
    }
    @if (ViewData["OGType"] != null)
    {
        <meta property="og:type" content="@Html.Raw(ViewData["OGType"])" />
    }
    else
    {
        <meta property="og:type" content="website" />
    }
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,600,700" rel="stylesheet"> <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" rel="stylesheet"> <link href="~/css/style-okurdostu.css" rel="stylesheet"/> <link href="~/css/bs-edited.css" rel="stylesheet"/> <link href="~/css/preloader.css" rel="stylesheet"/> <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body class="bg-white">
    <partial name="~/Views/Shared/_SpinnerPartial.cshtml" />
    <div class="container">
        @if (ViewData["AppMenu"]?.ToString() != "Hide")
        {
        <div class="sidebar pb-0">
            <div> <a class="@ViewData["BetaActiveClass"]" href="/beta"><i class="fas fa-home"></i> <span>Beta</span></a> </div><div> <a class="@ViewData["SearchActiveClass"]" href="/arama" id="search"><i class="fas fa-search"></i> <span>Arama</span></a> </div><div> <a class="@ViewData["NeedsActiveClass"]" href="/ihtiyaclar" id="ihtiyaclar"><i class="fas fa-layer-group"></i> <span>İhtiyaçlar</span></a> </div><div> <a class="@ViewData["UniversityActiveClass"]" href="/universiteler" id="universiteler"><i class="fas fa-school"></i> <span>Üniversiteler</span></a> </div>
            @if (IsAuthenticated)
            {
                <div>
                    @if (@HttpContextAccessor.HttpContext.User.Identity.GetPhoto() != null)
                    {
                        <a href="/@HttpContextAccessor.HttpContext.User.Identity.GetUsername()" id="profil"><i><img src="@HttpContextAccessor.HttpContext.User.Identity.GetPhoto()" class="rounded-pill" style="width:35px; height:35px;" /></i> <span>Profil</span></a>
                    }
                    else
                    {
                        <a href="/@HttpContextAccessor.HttpContext.User.Identity.GetUsername()" id="profil"><img src="~/svg/user.svg" class="rounded-pill" style="width:35px; height:35px;" /> <span>Profil</span></a>
                    }
                </div>
                <div><a data-toggle="modal" data-target="#LogoutModal" style="cursor:pointer;"><i class="fas fa-sign-out-alt"></i> <span>Çıkış yap</span></a></div>
            }
            else
            {
                <div> <a href="/girisyap"><i class="fas fa-sign-in-alt"></i> <span>Giriş yap</span></a> </div>}
        </div>
        }
    <div class="content">
        <div class="row">
            <div class="pt-3 pr-2 pl-2 pb-3 col rounded-custom shadow rounded-custom">
                @RenderBody()
            </div>
        </div>
        <div class="text-center mt-2 small"> <div><a class="od font-weight-bold" href="/">Okurdostu</a></div><div> <div class="row"> <div class="col"> @if (Context.Request.Path.Value.ToLower()=="/beta"){<a class="font-weight-bold text-black-50" href="" data-toggle="modal" data-target="#Feedback" style="cursor:pointer;">Geri bildirim</a>}else{<a class="font-weight-bold text-black-50" href="/beta#Feedback">Geri bildirim</a>}</div><div class="col"><a class="font-weight-bold text-black-50 " href="/kullanici-sozlesmesi">Kullanıcı sözleşmesi</a><br/><a class="font-weight-bold text-black-50 " href="/gizlilik-politikasi">Gizlilik politikası</a></div><div class="col"><a class="font-weight-bold text-black-50" href="/SSS">SSS</a></div></div></div></div>
    </div>
    </div>
    @if (IsAuthenticated)
    {
        <div class="modal fade" id="LogoutModal" tabindex="-1" role="dialog" aria-hidden="true"> <div class="modal-dialog modal-sm modal-dialog-centered" role="document"> <div class="modal-content" style="background: transparent;"> <div class="modal-body bg-light" style="border-radius: 25px;"> <p class="text-center font-weight-bold text-black-50"> Çıkış mı yapmak istiyorsunuz? </p><hr/> <div> @using (Html.BeginForm("Index", "Logout", FormMethod.Post)){<button type="submit" class="btn btn-secondary btn-block font-weight-bold rounded-custom"> Evet, çıkış yap </button>}<hr class="mb-2 mt-2"/> <button type="button" class="btn btn-outline-secondary btn-block rounded-custom font-weight-bold" data-dismiss="modal">Vazgeçtim</button> </div></div></div></div></div>
    }
 <script async src="~/js/bootstrap.min.js"> </script> <script async src="https://www.googletagmanager.com/gtag/js?id=UA-13125894-3"></script> <script>window.dataLayer=window.dataLayer || []; function gtag(){dataLayer.push(arguments);}gtag('js', new Date()); gtag('config', 'UA-13125894-3'); </script>
</body>
</html>

src/Okurdostu.Web/Views/Shared/_SpinnerPartial.cshtml
<div class="spinner-div" id="spinner-div" style="display:none;"><div class="spinner"><div class="bounce1"></div><div class="bounce2"></div><div class="bounce3"></div></div></div>

src/Okurdostu.Web/Views/Shared/_SweetAlertPartial.cshtml
<script src="~/lib/sweetalert/sweetalert2.all.min.js"></script>
<script>
    const Toast = Swal.mixin({ toast: true, position: 'top-end', timer: 2000, showConfirmButton: false, timerProgressBar: true, });
</script>

src/Okurdostu.Web/Views/Shared/_ValidateTokenPartial.cshtml
@Html.AntiForgeryToken()
<script>
        var validatetoken = $("input[name='__RequestVerificationToken']").val();
</script>